#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : keyring
Version  : 10.4.0
Release  : 36
URL      : https://pypi.debian.net/keyring/keyring-10.4.0.tar.gz
Source0  : https://pypi.debian.net/keyring/keyring-10.4.0.tar.gz
Summary  : Store and access your passwords safely.
Group    : Development/Tools
License  : MIT Python-2.0
Requires: keyring-bin
Requires: keyring-legacypython
Requires: keyring-python
Requires: Sphinx
Requires: pytest
Requires: secretstorage
BuildRequires : fs-python
BuildRequires : hgtools-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pycrypto-python
BuildRequires : pytest-runner-python
BuildRequires : python-dev
BuildRequires : python-keyczar-python
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : secretstorage
BuildRequires : setuptools
BuildRequires : setuptools_scm
Patch1: requires.patch

%description
.. image:: https://img.shields.io/pypi/v/keyring.svg
:target: https://pypi.org/project/keyring

%package bin
Summary: bin components for the keyring package.
Group: Binaries

%description bin
bin components for the keyring package.


%package legacypython
Summary: legacypython components for the keyring package.
Group: Default

%description legacypython
legacypython components for the keyring package.


%package python
Summary: python components for the keyring package.
Group: Default
Requires: keyring-legacypython

%description python
python components for the keyring package.


%prep
%setup -q -n keyring-10.4.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1505004793
python2 setup.py build -b py2
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python setup.py ptr || :
%install
export SOURCE_DATE_EPOCH=1505004793
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/keyring

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
